require('dotenv').config();
const mongoose = require('mongoose');

const SKU_MAPPING = [
  {"sku": "WHEAFREE-BAKERY-WHEAFREEP", "sub_category_name": "Bakery"},
  {"sku": "WHEAFREE-BAKERY-WHEAFREEP-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-02", "sub_category_name": "Bakery"},
  {"sku": "SKU-FIDALGO-BAKERY-FIDAL", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-03", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-02", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-04", "sub_category_name": "Bakery"},
  {"sku": "SKU-DRSCHAR-BAKERY-DRSCH", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-02", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-02", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-05", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-06", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-03", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-03", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-07", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-08", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-04", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-04", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-09", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-10", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-05", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-11", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-06", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-12", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-03", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-07", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-13", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-04", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-05", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-08", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-14", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-06", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-07", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-15", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-08", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-16", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-05", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-09", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-10", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-17", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-11", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-18", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-12", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-09", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-19", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-13", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-14", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-15", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-10", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-20", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-16", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-17", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-18", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-11", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-12", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-19", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-21", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-20", "sub_category_name": "Bakery"},
  {"sku": "SKU-ANMOLPRE-BAKERY-ANMO-13", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-22", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-21", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-23", "sub_category_name": "Bakery"},
  {"sku": "SKU-DRSCHAR-BAKERY-DRSCH-01", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-22", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-24", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-25", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-26", "sub_category_name": "Bakery"},
  {"sku": "SKU-SPRING-BAKERY-SPRING-06", "sub_category_name": "Bakery"},
  {"sku": "SKU-WHEAFREE-BAKERY-WHEA-23", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-27", "sub_category_name": "Bakery"},
  {"sku": "SKU-CHOCOLAT-BAKERY-CHOC-28", "sub_category_name": "Bakery"},
  {"sku": "SKU-RAWPRESS-BEVERA-RAWA", "sub_category_name": "Beverages"},
  {"sku": "SKU-RAWPRESS-BEVERA-RAWA-01", "sub_category_name": "Beverages"},
  {"sku": "SKU-REALTHAI-BEVERA-REAL", "sub_category_name": "Beverages"},
  {"sku": "SKU-REALTHAI-BEVERA-REAL-01", "sub_category_name": "Beverages"},
  {"sku": "SKU-SAVORLIF-CEREAL-SAVO", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-POST-CEREAL-POSTFRUI", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-DRSCHAR-CEREAL-DRSCH", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-WHEAFREE-CEREAL-WHEA", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-DRSCHAR-CEREAL-DRSCH-01", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-GULLON-CEREAL-GULLON", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA-01", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-BEWELL-CEREAL-BEWELL", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA-02", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-NOURISHO-CEREAL-NOUR", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA-03", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA-04", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-24MANTRA-CEREAL-24MA-05", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-ANMOLPRE-CEREAL-ANMO", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-DRSCHAR-CEREAL-DRSCH-02", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-DRSCHAR-CEREAL-DRSCH-03", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-ZEROG-CEREAL-ZEROGPU", "sub_category_name": "Cereals & Grains"},
  {"sku": "SKU-ORGRAN-CEREAL-ORGRAN", "sub_category_name": "Cereals & Grains"},
  {"sku": "WHEAFREE-COOKIE-WHEAFREEA", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "WHEAFREE-COOKIE-WHEAFREEP", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-CHOCOLAT-COOKIE-CHOC", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-PUREFOOD-COOKIE-PFDO", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-PUREFOOD-COOKIE-PFBA", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-PUREFOOD-COOKIE-PFST", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-PUREFOOD-COOKIE-PFCR", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIC", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIA", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIC-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIC-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIC-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-05", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-GULLON-COOKIE-GULLON", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-06", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIC-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIE", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIM", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIO", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIP", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-07", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-08", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIP-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-SAIFOODS-COOKIE-SAIZ", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-09", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-05", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-10", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-11", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-06", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-12", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-07", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-BEWELL-COOKIE-BEWELL", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-08", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-13", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-BEWELL-COOKIE-BEWELL-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-09", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-14", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-15", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-01", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-10", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-16", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-02", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-11", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-17", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-03", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-12", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-18", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-19", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-13", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-20", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-14", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-15", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-21", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-16", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-17", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-22", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-18", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-19", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-05", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-20", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-DRSCHAR-COOKIE-DRSCH-06", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-04", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-05", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-23", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-24", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-ANMOLPRE-COOKIE-ANMO-21", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-05", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHOLEFOO-COOKIE-WHOL-06", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-25", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-06", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-26", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-27", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-FIDALGO-COOKIE-FIDAL-07", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "SKU-WHEAFREE-COOKIE-WHEA-28", "sub_category_name": "Cookies & Biscuits"},
  {"sku": "ZEROG-COOKIN-ZEROGRAGIIDL", "sub_category_name": "Cooking Mix"},
  {"sku": "WHEAFREE-COOKIN-WHEAFREEB", "sub_category_name": "Cooking Mix"},
  {"sku": "WHEAFREE-COOKIN-WHEAFREEP", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ORGRAN-COOKIN-ORGRAN", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ORGRAN-COOKIN-ORGRAN-01", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ZEROG-COOKIN-ZEROGBH", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ZEROG-COOKIN-ZEROGHE", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-01", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-02", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-03", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-BEWELL-COOKIN-BEWELL", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-BEWELL-COOKIN-BEWELL-01", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ANMOLPRE-COOKIN-ANMO", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-04", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-BEWELL-COOKIN-BEWELL-02", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-BEWELL-COOKIN-BEWELL-03", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-05", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHOLEFOO-COOKIN-WHOL", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-WHEAFREE-COOKIN-WHEA-06", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ZEROG-COOKIN-ZEROGSO", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ZEROG-COOKIN-ZEROGDA", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ORGRAN-COOKIN-ORGRAN-02", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-ORGRAN-COOKIN-ORGRAN-03", "sub_category_name": "Cooking Mix"},
  {"sku": "SKU-24MANTRA-COOKIN-24MA", "sub_category_name": "Cooking Oil"},
  {"sku": "SKU-24MANTRA-COOKIN-24MA-01", "sub_category_name": "Cooking Oil"},
  {"sku": "SKU-24MANTRA-COOKIN-24MA-02", "sub_category_name": "Cooking Oil"},
  {"sku": "BEWELL-FLOUR-BEWELLSOFTCH", "sub_category_name": "Flour"},
  {"sku": "ZEROG-FLOUR-ZEROGTRIPLEG-", "sub_category_name": "Flour"},
  {"sku": "WHEAFREE-FLOUR-WHEAFREEBE", "sub_category_name": "Flour"},
  {"sku": "SKU-BEWELL-FLOUR-BEWELLS", "sub_category_name": "Flour"},
  {"sku": "SKU-WHOLEFOO-FLOUR-WHOLE", "sub_category_name": "Flour"},
  {"sku": "SKU-YOGI-FLOUR-YOGIGFREE", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGLIT", "sub_category_name": "Flour"},
  {"sku": "SKU-YOGI-FLOUR-YOGIGFREE-01", "sub_category_name": "Flour"},
  {"sku": "SKU-FIDALGO-FLOUR-FIDALG", "sub_category_name": "Flour"},
  {"sku": "SKU-SAVORLIF-FLOUR-SAVOR", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF", "sub_category_name": "Flour"},
  {"sku": "SKU-ANMOLPRE-FLOUR-ANMOL", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGBUC", "sub_category_name": "Flour"},
  {"sku": "SKU-YOGI-FLOUR-YOGIGFREE-02", "sub_category_name": "Flour"},
  {"sku": "SKU-DRGLUTEN-FLOUR-PLATI", "sub_category_name": "Flour"},
  {"sku": "SKU-SAIFOODS-FLOUR-SAIHE", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-01", "sub_category_name": "Flour"},
  {"sku": "SKU-SAIFOODS-FLOUR-SAIMU", "sub_category_name": "Flour"},
  {"sku": "SKU-SAIFOODS-FLOUR-SAIMU-01", "sub_category_name": "Flour"},
  {"sku": "SKU-DRGLUTEN-FLOUR-DRGLU", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-02", "sub_category_name": "Flour"},
  {"sku": "SKU-BEWELL-FLOUR-BEWELLR", "sub_category_name": "Flour"},
  {"sku": "SKU-DRGLUTEN-FLOUR-DRGLU-01", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-03", "sub_category_name": "Flour"},
  {"sku": "SKU-BEWELL-FLOUR-BEWELLC", "sub_category_name": "Flour"},
  {"sku": "SKU-BEWELL-FLOUR-BEWELLB", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-04", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN", "sub_category_name": "Flour"},
  {"sku": "SKU-BEWELL-FLOUR-BEWELLB-01", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-01", "sub_category_name": "Flour"},
  {"sku": "SKU-CHOCOLAT-FLOUR-CHOCO", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-02", "sub_category_name": "Flour"},
  {"sku": "SKU-WHOLEFOO-FLOUR-WHOLE-01", "sub_category_name": "Flour"},
  {"sku": "SKU-WHOLEFOO-FLOUR-WHOLE-02", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-03", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-05", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-04", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-05", "sub_category_name": "Flour"},
  {"sku": "SKU-ANMOLPRE-FLOUR-ANMOL-01", "sub_category_name": "Flour"},
  {"sku": "SKU-24MANTRA-FLOUR-24MAN-06", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-06", "sub_category_name": "Flour"},
  {"sku": "SKU-WHOLEFOO-FLOUR-WHOLE-03", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGHUL", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGMAI", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGRIT", "sub_category_name": "Flour"},
  {"sku": "SKU-ZEROG-FLOUR-ZEROGBRO", "sub_category_name": "Flour"},
  {"sku": "SKU-YESYOUCA-FLOUR-YESYO", "sub_category_name": "Flour"},
  {"sku": "SKU-WHOLEFOO-FLOUR-WHOLE-04", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-07", "sub_category_name": "Flour"},
  {"sku": "SKU-WHEAFREE-FLOUR-WHEAF-08", "sub_category_name": "Flour"},
  {"sku": "ZEROG-MASALA-ZEROGHING50G", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-ORGANICI-MASALA-ORGA", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-01", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-02", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-03", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-04", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-05", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-06", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-01", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-07", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-02", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-08", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-03", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-09", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-04", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-10", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-05", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-11", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-12", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-ANMOLPRE-MASALA-ANMO", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-06", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-13", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-BEWELL-MASALA-BEWELL-07", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-14", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-WHOLEFOO-MASALA-WHOL", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-15", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-16", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-17", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-18", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-19", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-20", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-24MANTRA-MASALA-24MA-21", "sub_category_name": "Masala / Condiments"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-01", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-137DEGRE-MILKRE-137D", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-02", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-03", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-04", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-05", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-SOGOOD-MILKRE-SOGOOD-06", "sub_category_name": "Milk Replacement"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL", "sub_category_name": "Noodles"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL-01", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMAINST", "sub_category_name": "Noodles"},
  {"sku": "SKU-WHEAFREE-NOODLE-WHEA", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMAINST-01", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMAWHOL", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMARICE", "sub_category_name": "Noodles"},
  {"sku": "SKU-CHOCOLAT-NOODLE-CHOC", "sub_category_name": "Noodles"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL-02", "sub_category_name": "Noodles"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL-03", "sub_category_name": "Noodles"},
  {"sku": "SKU-WHEAFREE-NOODLE-WHEA-01", "sub_category_name": "Noodles"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL-04", "sub_category_name": "Noodles"},
  {"sku": "SKU-PEACOCK-NOODLE-PEACO", "sub_category_name": "Noodles"},
  {"sku": "SKU-REALTHAI-NOODLE-REAL-05", "sub_category_name": "Noodles"},
  {"sku": "SKU-PEACOCK-NOODLE-PEACO-01", "sub_category_name": "Noodles"},
  {"sku": "SKU-BEWELL-NOODLE-BEWELL", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMARICE-01", "sub_category_name": "Noodles"},
  {"sku": "SKU-WHEAFREE-NOODLE-WHEA-02", "sub_category_name": "Noodles"},
  {"sku": "SKU-MAMA-NOODLE-MAMARICE-02", "sub_category_name": "Noodles"},
  {"sku": "ANMOLPRE-PASTA-ANMOLPREET", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-DRSCHAR-PASTA-DRSCHA", "sub_category_name": "Pasta"},
  {"sku": "SKU-DRSCHAR-PASTA-DRSCHA-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-02", "sub_category_name": "Pasta"},
  {"sku": "SKU-MAMY-PASTA-MAMYRICEP", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-03", "sub_category_name": "Pasta"},
  {"sku": "SKU-CHOCOLAT-PASTA-CHOCO", "sub_category_name": "Pasta"},
  {"sku": "SKU-MAMY-PASTA-MAMYRICEP-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-04", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-05", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-06", "sub_category_name": "Pasta"},
  {"sku": "SKU-WHEAFREE-PASTA-WHEAF", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-07", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-08", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-09", "sub_category_name": "Pasta"},
  {"sku": "SKU-WHEAFREE-PASTA-WHEAF-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-10", "sub_category_name": "Pasta"},
  {"sku": "SKU-WHEAFREE-PASTA-WHEAF-02", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-11", "sub_category_name": "Pasta"},
  {"sku": "SKU-NUTRAHI-PASTA-NUTRAH-12", "sub_category_name": "Pasta"},
  {"sku": "SKU-PEACOCK-PASTA-PEACOC", "sub_category_name": "Pasta"},
  {"sku": "SKU-ANMOLPRE-PASTA-ANMOL", "sub_category_name": "Pasta"},
  {"sku": "SKU-WHEAFREE-PASTA-WHEAF-03", "sub_category_name": "Pasta"},
  {"sku": "SKU-PEACOCK-PASTA-PEACOC-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-PEACOCK-PASTA-PEACOC-02", "sub_category_name": "Pasta"},
  {"sku": "SKU-ORGRAN-PASTA-ORGRANR", "sub_category_name": "Pasta"},
  {"sku": "SKU-ORGRAN-PASTA-ORGRANR-01", "sub_category_name": "Pasta"},
  {"sku": "SKU-ORGRAN-PASTA-ORGRANQ", "sub_category_name": "Pasta"},
  {"sku": "SKU-24MANTRA-PULSES-24MA", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-01", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-02", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-03", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-04", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-05", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-06", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-07", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-08", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-09", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-10", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-11", "sub_category_name": "Pulses"},
  {"sku": "SKU-24MANTRA-PULSES-24MA-12", "sub_category_name": "Pulses"},
  {"sku": "WHEAFREE-READYT-WHEAFREEP", "sub_category_name": "Ready to eat"},
  {"sku": "SKU-24MANTRA-RICE-24MANT", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-01", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-02", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-03", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-04", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-05", "sub_category_name": "Rice"},
  {"sku": "SKU-24MANTRA-RICE-24MANT-06", "sub_category_name": "Rice"},
  {"sku": "SKU-WHOLEFOO-RUSK-WHOLEF", "sub_category_name": "Rusk"},
  {"sku": "SKU-SAIFOODS-RUSK-SAICAK", "sub_category_name": "Rusk"},
  {"sku": "SKU-FIDALGO-RUSK-FIDALGO", "sub_category_name": "Rusk"},
  {"sku": "SKU-SAIFOODS-RUSK-SAIFOO", "sub_category_name": "Rusk"},
  {"sku": "SKU-SAIFOODS-RUSK-SAIFOO-01", "sub_category_name": "Rusk"},
  {"sku": "SKU-ANMOLPRE-RUSK-ANMOLP", "sub_category_name": "Rusk"},
  {"sku": "SKU-BEWELL-RUSK-BEWELLCA", "sub_category_name": "Rusk"},
  {"sku": "SKU-WHEAFREE-RUSK-WHEAFR", "sub_category_name": "Rusk"},
  {"sku": "SKU-ANMOLPRE-RUSK-ANMOLP-01", "sub_category_name": "Rusk"},
  {"sku": "SKU-WHEAFREE-RUSK-WHEAFR-01", "sub_category_name": "Rusk"},
  {"sku": "SKU-WHEAFREE-RUSK-WHEAFR-02", "sub_category_name": "Rusk"},
  {"sku": "SKU-ANMOLPRE-SAUCES-ANMO", "sub_category_name": "Sauces"},
  {"sku": "SKU-CORNITOS-SAUCES-CORN", "sub_category_name": "Sauces"},
  {"sku": "SKU-CORNITOS-SAUCES-CORN-01", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBACH", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAEG", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAOL", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBASO", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAGR", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAMA", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAMI", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBAPE", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBARE", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBASR", "sub_category_name": "Sauces"},
  {"sku": "SKU-VEEBA-SAUCES-VEEBASW", "sub_category_name": "Sauces"},
  {"sku": "SKU-ANMOLPRE-SAUCES-ANMO-01", "sub_category_name": "Sauces"},
  {"sku": "SKU-CHILZO-SAUCES-CHILZO", "sub_category_name": "Sauces"},
  {"sku": "SKU-CHILZO-SAUCES-CHILZO-01", "sub_category_name": "Sauces"},
  {"sku": "SKU-CHILZO-SAUCES-CHILZO-02", "sub_category_name": "Sauces"},
  {"sku": "SKU-EARTHWIS-SEEDSN-EART", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-EARTHWIS-SEEDSN-EART-01", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-24MANTRA-SEEDSN-24MA", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-24MANTRA-SEEDSN-24MA-01", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-24MANTRA-SEEDSN-24MA-02", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-24MANTRA-SEEDSN-24MA-03", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "SKU-24MANTRA-SEEDSN-24MA-04", "sub_category_name": "Seeds Nuts & Berries"},
  {"sku": "BEWELL-SNACKS-BEWELLDALPA", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIF", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIF-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-06", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIF-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-07", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-08", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIG", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-09", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-10", "sub_category_name": "Snacks"},
  {"sku": "SKU-EARTHWIS-SNACKS-EART", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-11", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIF-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-12", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-13", "sub_category_name": "Snacks"},
  {"sku": "SKU-SAIFOODS-SNACKS-SAIP", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-14", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-15", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-16", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-06", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-06", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-17", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-07", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-08", "sub_category_name": "Snacks"},
  {"sku": "SKU-KETTLEST-SNACKS-KETT", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-07", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-18", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-09", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-10", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-11", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-08", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-09", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-19", "sub_category_name": "Snacks"},
  {"sku": "SKU-24MANTRA-SNACKS-24MA", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-10", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-20", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-12", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-13", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-21", "sub_category_name": "Snacks"},
  {"sku": "SKU-BEWELL-SNACKS-BEWELL-11", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHOCOLAT-SNACKS-CHOC-06", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-22", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-23", "sub_category_name": "Snacks"},
  {"sku": "SKU-BRB-SNACKS-BRBPOTATO", "sub_category_name": "Snacks"},
  {"sku": "SKU-CORNITOS-SNACKS-CORN-24", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-14", "sub_category_name": "Snacks"},
  {"sku": "SKU-BRB-SNACKS-BRBPOTATO-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-BRB-SNACKS-BRBRICEPO", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-15", "sub_category_name": "Snacks"},
  {"sku": "SKU-BRB-SNACKS-BRBRICEPO-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHEFURBA-SNACKS-CHEF", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-16", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHEFURBA-SNACKS-CHEF-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL-04", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHEFURBA-SNACKS-CHEF-02", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHOLEFOO-SNACKS-WHOL-05", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-17", "sub_category_name": "Snacks"},
  {"sku": "SKU-ANMOLPRE-SNACKS-ANMO-06", "sub_category_name": "Snacks"},
  {"sku": "SKU-CHEFURBA-SNACKS-CHEF-03", "sub_category_name": "Snacks"},
  {"sku": "SKU-LIFEOATS-SNACKS-LIFE", "sub_category_name": "Snacks"},
  {"sku": "SKU-KETTLEST-SNACKS-KETT-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-WHEAFREE-SNACKS-WHEA-18", "sub_category_name": "Snacks"},
  {"sku": "SKU-LIFEOATS-SNACKS-LIFE-01", "sub_category_name": "Snacks"},
  {"sku": "SKU-MAMA-SOUP-MAMAINSTAN", "sub_category_name": "Soup"},
  {"sku": "SKU-MAMA-SOUP-MAMACUPRIC", "sub_category_name": "Soup"},
  {"sku": "SKU-MAMA-SOUP-MAMAINSTAN-01", "sub_category_name": "Soup"},
  {"sku": "SKU-ORGANICI-SOUP-ORGANI", "sub_category_name": "Soup"},
  {"sku": "SKU-ZEROG-SUPPLE-ZEROGPO", "sub_category_name": "Supplements"},
  {"sku": "SKU-ZEROG-SUPPLE-ZEROGGR", "sub_category_name": "Supplements"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA", "sub_category_name": "Sweets"},
  {"sku": "SKU-CHOCOLAT-SWEETS-CHOC", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-01", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-02", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-03", "sub_category_name": "Sweets"},
  {"sku": "SKU-ANMOLPRE-SWEETS-ANMO", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-04", "sub_category_name": "Sweets"},
  {"sku": "SKU-ANMOLPRE-SWEETS-ANMO-01", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-05", "sub_category_name": "Sweets"},
  {"sku": "SKU-ANMOLPRE-SWEETS-ANMO-02", "sub_category_name": "Sweets"},
  {"sku": "SKU-WHEAFREE-SWEETS-WHEA-06", "sub_category_name": "Sweets"}
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');
  const db = mongoose.connection.db;

  const subcats = await db.collection('subcategories').find({}).toArray();
  const subcatMap = {};
  subcats.forEach(s => { subcatMap[s.name.trim().toLowerCase()] = s._id; });

  let updated = 0, notFound = 0, noSubcat = 0;

  for (const { sku, sub_category_name } of SKU_MAPPING) {
    const subcatId = subcatMap[sub_category_name.trim().toLowerCase()];
    if (!subcatId) {
      console.log('No subcategory found for:', sub_category_name);
      noSubcat++;
      continue;
    }
    const result = await db.collection('products').updateOne(
      { sku },
      { $set: { sub_category: subcatId } }
    );
    if (result.matchedCount === 0) {
      notFound++;
    } else {
      updated++;
    }
  }

  console.log('---');
  console.log('Updated:', updated);
  console.log('SKU not found in DB:', notFound);
  console.log('Subcategory name not found:', noSubcat);
  await mongoose.disconnect();
  console.log('Done.');
}

run().catch(console.error);
